import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configure style aesthetics
plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams.update({
    'font.size': 11,
    'font.family': 'sans-serif',
    'axes.labelsize': 12,
    'axes.titlesize': 14,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'figure.titlesize': 16
})

def generate_visualizations(csv_path, output_dir):
    """Generates a complete suite of publication-ready visualizations."""
    df = pd.read_csv(csv_path)
    df['Order_Date'] = pd.to_datetime(df['Order_Date'])
    
    plots_dir = os.path.join(output_dir, "plots")
    os.makedirs(plots_dir, exist_ok=True)
    
    palette = sns.color_palette("muted")
    
    # 1. Bar Chart: Revenue by Category & Region
    fig, ax = plt.subplots(figsize=(10, 6))
    cat_region = df.groupby(['Category', 'Region'])['Sales'].sum().reset_index()
    sns.barplot(data=cat_region, x='Category', y='Sales', hue='Region', palette='viridis', ax=ax)
    ax.set_title("Total Revenue by Product Category & Region", fontweight='bold', pad=15)
    ax.set_xlabel("Product Category")
    ax.set_ylabel("Total Sales ($)")
    ax.yaxis.set_major_formatter('${x:,.0f}')
    plt.legend(title="Region", frameon=True)
    plt.tight_layout()
    plt.savefig(os.path.join(plots_dir, "1_bar_chart_category_region.png"), dpi=300)
    plt.close()
    
    # 2. Line Chart: Monthly Sales & Profit Trends
    df['YearMonth'] = df['Order_Date'].dt.to_period('M')
    monthly_trend = df.groupby('YearMonth').agg({'Sales': 'sum', 'Profit': 'sum'}).reset_index()
    monthly_trend['YearMonth'] = monthly_trend['YearMonth'].astype(str)
    
    fig, ax1 = plt.subplots(figsize=(12, 6))
    ax2 = ax1.twinx()
    
    l1 = ax1.plot(monthly_trend['YearMonth'], monthly_trend['Sales'], color='#1f77b4', marker='o', linewidth=2.5, label='Monthly Revenue ($)')
    l2 = ax2.plot(monthly_trend['YearMonth'], monthly_trend['Profit'], color='#2ca02c', marker='s', linewidth=2.5, linestyle='--', label='Monthly Profit ($)')
    
    ax1.set_title("Monthly Revenue and Profit Performance Trend", fontweight='bold', pad=15)
    ax1.set_xlabel("Month")
    ax1.set_ylabel("Total Revenue ($)", color='#1f77b4')
    ax2.set_ylabel("Total Profit ($)", color='#2ca02c')
    ax1.tick_params(axis='x', rotation=45)
    
    # Combined legend
    lines = l1 + l2
    labels = [l.get_label() for l in lines]
    ax1.legend(lines, labels, loc='upper left', frameon=True)
    
    plt.tight_layout()
    plt.savefig(os.path.join(plots_dir, "2_line_chart_monthly_trends.png"), dpi=300)
    plt.close()
    
    # 3. Donut/Pie Chart: Revenue Share by Customer Segment
    fig, ax = plt.subplots(figsize=(8, 8))
    segment_share = df.groupby('Segment')['Sales'].sum()
    colors = ['#4c72b0', '#55a868', '#c44e52']
    wedges, texts, autotexts = ax.pie(
        segment_share, 
        labels=segment_share.index, 
        autopct='%1.1f%%',
        startangle=140, 
        colors=colors,
        pctdistance=0.75,
        wedgeprops=dict(width=0.4, edgecolor='w', linewidth=2)
    )
    plt.setp(autotexts, size=11, weight="bold", color="white")
    ax.set_title("Market Revenue Share by Customer Segment", fontweight='bold', pad=15)
    plt.tight_layout()
    plt.savefig(os.path.join(plots_dir, "3_pie_chart_segment_share.png"), dpi=300)
    plt.close()
    
    # 4. Histogram & KDE: Order Value Distribution
    fig, ax = plt.subplots(figsize=(10, 6))
    sns.histplot(df['Sales'], kde=True, color='#2b5c8f', bins=30, ax=ax)
    ax.axvline(df['Sales'].mean(), color='red', linestyle='--', linewidth=2, label=f"Mean Sales: ${df['Sales'].mean():.2f}")
    ax.axvline(df['Sales'].median(), color='green', linestyle='-', linewidth=2, label=f"Median Sales: ${df['Sales'].median():.2f}")
    ax.set_title("Order Value Distribution & Central Tendency", fontweight='bold', pad=15)
    ax.set_xlabel("Order Value ($)")
    ax.set_ylabel("Order Count")
    ax.legend(frameon=True)
    plt.tight_layout()
    plt.savefig(os.path.join(plots_dir, "4_histogram_order_distribution.png"), dpi=300)
    plt.close()
    
    # 5. Scatter Plot: Quantity Sold vs Sales Amount with Category Hue
    fig, ax = plt.subplots(figsize=(10, 6))
    sns.scatterplot(data=df, x='Quantity', y='Sales', hue='Category', style='Segment', s=80, alpha=0.8, palette='Set2', ax=ax)
    ax.set_title("Quantity Sold vs. Revenue Generated by Category", fontweight='bold', pad=15)
    ax.set_xlabel("Quantity Units Sold")
    ax.set_ylabel("Order Revenue ($)")
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    plt.savefig(os.path.join(plots_dir, "5_scatter_plot_quantity_vs_sales.png"), dpi=300)
    plt.close()

    print(f"SUCCESS: Visualizations generated and saved to '{plots_dir}'.")


if __name__ == "__main__":
    base_dir = os.path.dirname(os.path.abspath(__file__))
    sales_data = os.path.join(os.path.dirname(base_dir), "Task_2_EDA", "sales_dataset.csv")
    generate_visualizations(sales_data, base_dir)
